# Upstream changes from _extends are only recognized when modifications are made to this file in the default branch.
_extends: .github
repository:
  name: aws-route53-resolver-dns-firewall
  description: This component is responsible for provisioning [Route 53 Resolver DNS Firewall](https://docs
  homepage: https://cloudposse.com/accelerate
  topics: terraform, terraform-component
