# Upstream changes from _extends are only recognized when modifications are made to this file in the default branch.
_extends: .github
repository:
  name: aws-route53-resolver-dns-firewall
  description: This component is responsible for provisioning Route 53 Resolver DNS Firewall resources, including Route 53 Resolver DNS Firewall, domain lists, firewall rule groups, firewall rules, and logging configuration.
  homepage: https://cloudposse.com/accelerate
  topics: terraform, terraform-component
